version: '3.7'
services:
  mongodb:
    image: mongo
    ports: 
      - 27017:27017
    volumes: 
      - mongodata:/data/db 
    networks: 
      - local
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD} 
  db_server:
    build: ./DB-Server
    ports:
      - 3001:3001
    volumes:
      - ./logs/DB-Server:/code/logs
    environment: 
      - MONGO_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017
      - LIVE_TRADING_MANAGER_BASE_URL=http://live_trading_manager:3004
      - ID=db_server_123
      - AUTHENTICATION_TOKEN=${AUTHENTICATION_TOKEN}
    depends_on:
      - mongodb
      - live_trading_manager
    networks: 
      - local
    restart: unless-stopped
  ml_server:
    build: ./ML-For-Trading-Bot
    ports:
      - 3002:3002
    volumes:
      - ./logs/ML-For-Trading-Bot:/code/flaskr/logs
    environment: 
      - DB_SERVER_API_BASE=http://db_server:3001
      - PORT=3002
      - SOCKET_URL=http://live_trading_manager:3004
      - ID=ML_Server_1
      - AUTHENTICATION_TOKEN=${AUTHENTICATION_TOKEN}
    depends_on:
      - live_trading_manager
    networks: 
      - local
    restart: unless-stopped
  # gekko:
  #   build: ./Gekko
  #   # ports:
  #   #   - 3003:3003
  #   environment: 
  #     - LIVE_TRADE_MANAGER_BASE_API=http://live_trading_manager:3004
  #   volumes:
  #     - ./logs/Gekko:/usr/src/app/logs
  #     - ./save_info/default:/usr/src/app/save_info
  #   depends_on:
  #     - ml_server
  #     - live_trading_manager
  #   networks: 
  #     - local
  live_trading_manager:
    build: ./live-trading-manager
    ports:
      - 3004:3004
    volumes:
      - ./logs/live-trading-manager:/code/logs
    environment: 
      - MONGO_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017
      - ML_SERVER_BASE_API=http://ml_server:3002
      - DOCKER_HOST=dockerhost
      - AUTHENTICATION_TOKEN=${AUTHENTICATION_TOKEN}
    depends_on:
      - mongodb
    networks: 
      - local
    restart: unless-stopped
  ui:
    build: ./UI
    ports:
      - 3005:80
    environment:
      - REACT_APP_LIVE_TRADING_MANAGER_HOST=http://35.186.150.9:3004
    networks: 
      - local
    restart: unless-stopped
  dockerhost:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
    networks: 
      - local
volumes:
  mongodata:
networks: 
  local: